### ISSUE TITLE
Can’t start Grafana while offline.

### ISSUE THREAD

**Issue by durib** [victronenergy/venus-grafana#15]
Grafana is trying to update plugins when it first starts, if you are not connected to the internet then the Grafana container fails to start. 

_grafana-1   | Error: ✗ Get "https://grafana.com/api/plugins/repo/simpod-json-datasource": dial tcp: lookup grafana.com on 127.0.0.11:53: server misbehaving
..
..
grafana-1 exited with code 1_

**Comment by mman** [comment]
Good point @durib. Let me take a look how to best address this. The plug-in can be pre downloaded so that it is not fetched every time from the internet.

**Comment by mman** [comment]
So this fix will require for us to re-bundle the plugin in question into the build, but it's a fairly stable thing so I will address this later today.

**Comment by mman** [comment]
@durib Could you please `git pull` and rebuild your docker image and try it for me? It should work now flawlessly since the plugin is no longer downloaded from the Grafana every time the image is created for the first time, but is rather bundled directly.

**Comment by JCAguilera** [comment]
Hi, I installed all of this using the docker-compose file mentioned in the quick start. How can I fix this error? I don't know how to compile a docker image.

**Comment by mman** [comment]
@JCAguilera In your docker compose yaml, reference a version 1.1.0 of  `victronenergy/venus-grafana:1.1.0` and `victronenergy/venus-influx-loader:1.1.0` and it should work. Please paste here your `docker-compose.yaml` so that I can take a look if that does not work for you.

**Comment by durib** [comment]
> @durib Could you please `git pull` and rebuild your docker image and try it for me? It should work now flawlessly since the plugin is no longer downloaded from the Grafana every time the image is created for the first time, but is rather bundled directly.

Thanks @mman, I can confirm all the services start while offline, sorry it took me so long to get back to you, haven't been out to the cabin for a few months and have been waiting to test it on the real system but that's going to have to wait as life has got it the way again... I do note that the example docker-compose.yaml is using the develop tag, which I had assumed was latest, but I had to swap to 1.1.

Thanks again for the great work 👍

**Comment by mman** [comment]
@durib Yeah, the `develop` tag was present in the examples as aways getting the latest features but now that we are stable I should just update the example with exact version.
