### ISSUE TITLE
FR - Add possibility to Venus Influx Loader to connect to local InfluxDB and Grafana Instances

### ISSUE THREAD

**Issue by Dunnenj** [victronenergy/venus-grafana#31]
I already have a server running InfluxDB v2 and another server running Grafana. Is it possible to add to the configuration of the Venus Influx Loader that data can be written to a local Influx DB server? 

I prefer to keep all my buckets at  one location.

**Comment by mman** [comment]
@Dunnenj Using your own Grafana server is super easy, simply configure an InfluxDB datasource and if necessary add a predefined dashboards or create your own. The datasource and dashboards are here: https://github.com/victronenergy/venus-grafana/tree/main/grafana.

As for Influx, we currently support only Version 1.8 to cover wide range of devices, Influx 2 and 3 support is documented and planned but low priority. Please see https://github.com/victronenergy/venus-influx-loader/issues/33 and  https://github.com/victronenergy/venus-influx-loader/issues/34 for a discussion.
