### ISSUE TITLE
mapping of "state" numeric values to strings

### ISSUE THREAD

**Issue by intelliIT** [victronenergy/venus-grafana#36]
im looking for an official mapping of the _**state**_ numeric values e.g. `system/Dc/Battery/State` to a string value, e.g. `charging`.

i found some [mappings](https://github.com/sfstar/hass-victron/blob/1ec1567e5a958e1b2a7910d2ab2bce752b663a7b/custom_components/victron/const.py#L160) in the [homeassistant integration](https://github.com/sfstar/hass-victron/tree/main) via modbustcp and wanted to confirm if they are valid or rather the same.
i want to extend the dashboard with some information.

**Comment by mman** [comment]
Here is another publicly available mapping that may help:

https://github.com/victronenergy/venus-html5-app/blob/2eea85bb33eafbb8a18bf180bba27c5933eae8b5/src/app/utils/constants.js#L5
