### ISSUE TITLE
Where are the images?

### ISSUE THREAD

**Issue by nadrog** [victronenergy/venus-grafana#8]
I just tried to run the docker compose and the images are not available under victronenergy. I did find them under https://hub.docker.com/u/sodaengine.

**Comment by mman** [comment]
@nadrog The official images will be pushed to https://hub.docker.com/u/victronenergy at some point during the next weeks after we tag 1.0 and make sure everything is ready. For now feel free to use my personal images you found and report any issues that you may find... thanks!

**Comment by mman** [comment]
@nadrog The 1.0 of Venus Influx Loader and Venus Grafana has been released and docker images are now available.

https://hub.docker.com/r/victronenergy/venus-influx-loader/tags

https://hub.docker.com/r/victronenergy/venus-grafana/tags

Announcement post will follow up in the next days...
